name: Playwright Tests

on:
  workflow_call:
    inputs:
      base_url:
        type: string
        required: true
jobs:
  run-e2e-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
        id: cache
        with:
          path: |
            README.md
          lookup-only: true
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml', 'components/**', 'api/**', 'app.vue', 'requirements.txt', 'e2e/**') }}-smoke-tests
      - uses: pnpm/action-setup@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          version: 9
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm i --frozen-lockfile
      - name: Install playwright browsers
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps
      - name: Run tests
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm test:e2e
        env:
          PLAYWRIGHT_BASE_URL: ${{ inputs.base_url }}
      - uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4
        if: always() && steps.cache.outputs.cache-hit != 'true'
        with:
          name: playwright-test-results
          path: test-results/
