name: Playwright Tests

on:
  workflow_call:
    inputs:
      base_url:
        type: string
        required: true
jobs:
  run-e2e-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Install playwright browsers
        run: pnpm dlx playwright install --with-deps
      - name: Run tests
        run: pnpm test:e2e
        env:
          PLAYWRIGHT_BASE_URL: ${{ inputs.base_url }}
      - uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4
        if: always()
        with:
          name: playwright-test-results
          path: test-results/
