name: Playwright Tests

on:
  workflow_call:
    inputs:
      enviromnent_url:
        description: 'The URL of the production deployment'
        required: true
        type: string
jobs:
  run-e2e-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Install playwright browsers
        run: pnpm dlx playwright install --with-deps
      - name: Run tests
        run: pnpm test:e2e
        env:
          PLAYWRIGHT_BASE_URL: ${{ inputs.enviromnent_url }}
      - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
        if: always()
        with:
          name: playwright-test-results
          path: test-results/
