name: Playwright Tests

on:
  workflow_call:
    inputs:
      base_url:
        type: string
        required: true
jobs:
  run-e2e-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Install playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Run tests
        run: pnpm test:e2e
        env:
          PLAYWRIGHT_BASE_URL: ${{ inputs.base_url }}
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        if: always()
        with:
          name: playwright-test-results
          path: test-results/
