name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_call:
    outputs:
      url:
        description: 'The URL of the production deployment'
        value: ${{ jobs.Deploy-Production.outputs.url }}
jobs:
  Deploy-Production:
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.vercel-deploy.outputs.preview_url}}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
        id: cache
        with:
          path: |
            README.md
          lookup-only: true
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml', 'components/**', 'api/**', 'app.vue', 'requirements.txt', 'e2e/**') }}-deploy-prod
      - uses: pnpm/action-setup@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          version: 9
      - name: Install Vercel CLI
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --global vercel@latest
      - name: Pull Vercel Environment Information
        if: steps.cache.outputs.cache-hit != 'true'
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - uses: chrnorm/deployment-action@55729fcebec3d284f60f5bcabbd8376437d696b1 # v2
        id: deployment
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          initial-status: in_progress
      - name: Deploy Project Artifacts to Vercel
        id: vercel-deploy
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --archive=tgz > deployment-url.txt
          cat deployment-url.txt
          echo "preview_url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT
      - name: Debug github output
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo ${{ steps.vercel-deploy.outputs.preview_url }}
      - name: Update deployment status (success)
        if: success() && steps.cache.outputs.cache-hit != 'true'
        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.vercel-deploy.outputs.preview_url }}
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure() && steps.cache.outputs.cache-hit != 'true'
        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.vercel-deploy.outputs.preview_url }}
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
