name: Build and Test

on:
  push:
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build app
        run: pnpm run build
      - name: Run tests
        run: pnpm run test
