name: Build and Test

on:
  push:
    branches-ignore:
      - 'main'
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        id: cache
        with:
          path: |
            dist
          lookup-only: true
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml', 'components/**', 'api/**', 'app.vue', 'requirements.txt') }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm i --frozen-lockfile
      - name: Lint app
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm run lint
      - name: Build app
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm run build
      - name: Run tests
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm run test
  deploy:
    needs: [build-and-test]
    permissions:
      deployments: write
    uses: './.github/workflows/on_branch_deploy_preview_to_vercel.yaml'
    secrets: inherit
  smoke-test:
    needs: [deploy]
    uses: './.github/workflows/on_deploy_run_e2e.yaml'
    with:
      base_url: ${{ needs.deploy.outputs.url }}
