name: Build and Test

on:
  push:
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build app
        run: pnpm run build
      - name: Run tests
        run: pnpm run test
  deploy:
    needs: [build-and-test]
    if: github.ref == 'refs/heads/main'
    permissions:
      deployments: write
    uses: './.github/workflows/on_main_deploy_to_vercel.yaml'
    secrets: inherit
  smoke-test:
    needs: [deploy]
    uses: './.github/workflows/on_deploy_run_e2e.yaml'
    with:
      base_url: ${{ needs.deploy.outputs.url }}
