name: Deploy and E2E Test

on:
  workflow_call:
jobs:
  deploy:
    uses: './.github/workflows/on_main_deploy_to_vercel.yaml'
  run-e2e-tests:
    uses: './.github/workflows/on_deploy_run_e2e.yaml'
    with:
      enviromnent_url: ${{ needs.deploy.outputs.url }}
